site_name: Notas Musicais
repo_url: https://github.com/Lyarkh/Notas_Musicais
repo_name: Lyarkh/Notas_Musicais
edit_uri: tree/main/docs

theme:
  name: material
  language: pt-BR
  logo: assets/logo.png
  favicon: assets/logo.png

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css

watch:
  - notas_musicais
  
plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [notas_musicais]